/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from '../../src/modules';
import * as import2 from '@angular/core/src/di/injector';
class LocalForageModuleInjector extends import0.NgModuleInjector<import1.LocalForageModule> {
  _LocalForageModule_0:import1.LocalForageModule;
  constructor(parent:import2.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  createInternal():import1.LocalForageModule {
    this._LocalForageModule_0 = new import1.LocalForageModule();
    return this._LocalForageModule_0;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import1.LocalForageModule)) { return this._LocalForageModule_0; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const LocalForageModuleNgFactory:import0.NgModuleFactory<import1.LocalForageModule> = new import0.NgModuleFactory(LocalForageModuleInjector,import1.LocalForageModule);